### PR TITLE
Identify state labels

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**
This can be used to detect the target state based on the label on the state.

### CODE REVIEW

**Comment by Vipul-Cariappa** [comment]
I have also modified the submodule (https://github.com/pranshugaba/partial-exploration/pull/4/files#diff-e94757ef56fe3697baf251cc6f897b646d7cd7e656e0fa2f36ee750a8e8d89ed). But it is not reflected in the GitHub's diff. Should we need to fork the submodules to modify it?

**Comment by Vipul-Cariappa** [comment]
Reminder; The necessary changes to the submodule repository may not be applied.

**Comment by pranshugaba** [comment]
Thanks, I am in the process of changing the submodule to a regular directory. I will apply the changes in the submodule after that.

**Comment by pranshugaba** [comment]
I am facing issues removing submodules because this commit includes changes to the submodule. I am reverting the repository to before the merge, will remove submodules, and then apply this commit.

**Comment by Vipul-Cariappa** [comment]
It may not be that simple. I guess I will have to open a new PR. According to the changes you make removing the submodule. This PR's commit has changes into the submodule, it may not be mergable after removing the submodule.

**Comment by pranshugaba** [comment]
I have changed the submodule into a regular repository. I deleted the old branch "reach-check" with the submodule and have created a new branch "target" without the submodule. I have also included the changes that you have submitted in this pull request.

**Comment by pranshugaba** [comment]
Now there is an error when carrying out the .\gradlew compileJava step. I need to see what changed from the previous version with submodules.

**Pull request merged**
